SunnyRent_ADO.NET_Project/SunnyRent/SunnyRent/Models/House.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SunnyRent.Models
{
    public class House
    {     
        public int Id { get; set; }

        [Required(ErrorMessage ="House type field is required.")]
        [Display(Name = "Property Type")]
        public HouseType HouseType { get; set; }
       // public byte HouseTypeId { get; set; }

        [Required(ErrorMessage = "Rate field is required.")]
        public double Rate { get; set; }

        [Required(ErrorMessage = "Name field is required.")]
        public string Name { get; set; }

        public string Description { get; set; }

        public List<Image> Image { get; set; }

        [Required(ErrorMessage = "Address field is required.")]
        public string Address { get; set; }

        
        public bool TV { get; set; }

        
        public bool Pet { get; set; }

        
        public bool BBQ { get; set; }

       
        public bool FirePlace { get; set; }

       
        public bool AccessToWater { get; set; }

        
        public bool Pool { get; set; }

       
        public bool Smoking { get; set; }

       
        public bool WiFi { get; set; }
    }
}

SunnyRent_ADO.NET_Project/SunnyRent/SunnyRent/Models/HouseType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SunnyRent.Models
{
    public class HouseType
    {
        public byte Id { get; set; }
        public string Type { get; set; }
    }
}

SunnyRent_ADO.NET_Project/SunnyRent/SunnyRent/Controllers/HousesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SunnyRent.Models;
using System.Data.Entity;
using SunnyRent.ViewModel;

namespace SunnyRent.Controllers
{
    public class HousesController : Controller
    {
        private ApplicationDbContext _context;

        public HousesController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Houses
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cottages()
        {
            string viewName = "CustomerView";

            if (User.IsInRole(RoleNames.CanManageMedia))
                viewName = "AdminView";
            var house = _context.Houses.Include(h => h.Image).ToList();
            
            return View(viewName,house);
        }

        public ActionResult Details(int? id)
        {
            string viewName = "CustomerDetailsView";

            if (User.IsInRole(RoleNames.CanManageMedia))
                viewName = "AdminDetailsView";

            if (!id.HasValue)
            {
                return HttpNotFound();
            }
            //var house = _context.Houses.Include(h => h.HouseType).SingleOrDefault(h => h.Id == id);
           // var viewModel = _context.Reservations.Include(r => r.House).Where(r => r.HouseId == id).ToList();

            
            var viewModel = new HouseReservationViewModel
            {
                House = _context.Houses.Include(h => h.HouseType).Include(h => h.Image).SingleOrDefault(h => h.Id == id),
                Reservations = _context.Reservations.Include(r => r.House).Where(r => r.HouseId == id).ToList()
            };
            

            if (viewModel == null)
            {
                return HttpNotFound();
            }

            return View(viewName,viewModel);
        }
       
        //This action will display a confirm message to the user to cinfirm the delete operation
        public ActionResult Delete(int? id)
        {
            if (!id.HasValue)
                return HttpNotFound();

            var house = _context.Houses.Include(h => h.HouseType).SingleOrDefault(h => h.Id == id);

            if (house == null)
                return HttpNotFound();

            return View(house);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var house = _context.Houses.Find(id);
            var images = _context.Images.Where(i => i.HouseId == id).ToList();
            foreach(Image image in images)
            {
                _context.Images.Remove(image);
            }
            _context.Houses.Remove(house);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        //Edit customer details
        public ActionResult Edit(int id)
        {
            var houseInDB = _context.Houses.SingleOrDefault(h => h.Id == id);

            //if (houseInDB == null)
            //    return HttpNotFound();

            var viewModel = new HouseFormViewModel()
            {
                House = houseInDB,
                HouseTypes = _context.HouseTypes.ToList()
            };

            return View("HouseForm", viewModel);
        }

        //Get action to load the form (1)
        public ActionResult New()
        {
            var viewModel = new HouseFormViewModel
            {
                House = new House(),
                HouseTypes = _context.HouseTypes.ToList()
            };
            return View("HouseForm", viewModel);
        }

        //Post action to save data from my form (2)            
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(House house)
        {
            //Check if the form is valid
            if (!ModelState.IsValid)
            {
                //Return the same form back to the user
                var viewModel = new HouseFormViewModel
                {
                    House = house,
                    HouseTypes = _context.HouseTypes.ToList()
                };
                return View("HouseForm", viewModel);
            }

            //new house
            if (house.Id == 0)
            {
                _context.Houses.Add(house);
            }
            else
            {
                var houseInDB = _context.Houses.Single(h => h.Id == house.Id);

                //Manual update
                houseInDB.Rate = house.Rate;
                houseInDB.Name = house.Name;
                houseInDB.Description = house.Description;
                houseInDB.Address = house.Address;
                houseInDB.TV = house.TV;
                houseInDB.Pet = house.Pet;
                houseInDB.BBQ = house.BBQ;
                houseInDB.FirePlace = house.FirePlace;
                houseInDB.AccessToWater = house.AccessToWater;
                houseInDB.Pool = house.Pool;
                houseInDB.Smoking = house.Smoking;
                houseInDB.WiFi = house.WiFi;
                houseInDB.HouseType = house.HouseType;

                //imageInDB.ImageName = image.ImageName;
                //imageInDB.ImagePath = image.ImagePath;
                //TryUpdateModel(houseInDB);
            }

            _context.SaveChanges();
            return RedirectToAction("Cottages", "Houses");
        }

        [HttpPost]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> uploads)
        {
            foreach (var file in uploads)
            {
                if (file != null)
                {
                    // we get the name of file
                    string fileName = System.IO.Path.GetFileName(file.FileName);
                    // save file into folder of our project
                    file.SaveAs(Server.MapPath("~/Photoes/Uploaded/" + fileName));
                }
            }

            return RedirectToAction("HouseForm", "Houses");
        }

        [HttpPost]
        public ActionResult HouseForm(IEnumerable<HttpPostedFileBase> uploads, House house)
        {
            List<Image> imageList = new List<Image>();

            foreach (var file in uploads)
            {
                if (file != null)
                {
                    // we get the name of file
                    string fileName = System.IO.Path.GetFileName(file.FileName);
                    // save file into folder of our project
                    file.SaveAs(Server.MapPath("~/Photoes/Uploaded/" + fileName));
                    Image Image = new Image
                    {
                        ImageName = System.IO.Path.GetFileName(file.FileName),
                        ImagePath = "~/Photoes/Uploaded/" + fileName,
                        HouseId = house.Id
                    };
                    _context.Images.Add(Image);
                    _context.SaveChanges();

                    imageList.Add(Image);
                }

            }

            var viewModel = new HouseFormViewModel
            {
                House = house,
                HouseTypes = _context.HouseTypes.ToList(),
               // ImageList = imageList
            };



            return View(viewModel);
        }


    }
}

SunnyRent_ADO.NET_Project/SunnyRent/SunnyRent/Controllers/ReservationsController.cs
using SunnyRent.Models;
using SunnyRent.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;


namespace SunnyRent.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {
        private ApplicationDbContext _context;

        public ReservationsController()
        {
            _context = new ApplicationDbContext();
        }


        // GET: Reservations
        public ActionResult Book(int id)
        {
            var viewModel = new ReservationFormViewModel
            {
                House = _context.Houses.SingleOrDefault(h => h.Id == id)
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Book(ReservationFormViewModel reservationFormViewModel)
        {
            //Check if the form is valid
            //if (!ModelState.IsValid)
            //{
            //    //Return the same form back to the user
            //    var viewModel = new ReservationFormViewModel
            //    {
            //        House = _context.Houses.SingleOrDefault(h => h.Id == reservationFormViewModel.House.Id)
            //    };
            //    return View(viewModel);
            //}

            var userName = User.Identity.GetUserName();
            //dbContext.YourTable.Where(x => x.UserId = userId);
            var record = new Reservation()
            {
                CustomerName = userName,                
                House = _context.Houses.Single(h => h.Id == reservationFormViewModel.House.Id),
                CheckIn = reservationFormViewModel.Reservation.CheckIn,
                CheckOut = reservationFormViewModel.Reservation.CheckOut,
                NumberOfGuests = reservationFormViewModel.Reservation.NumberOfGuests
            };

            _context.Reservations.Add(record);
            _context.SaveChanges();


            return RedirectToAction("Cottages", "Houses");


        }
    }
}

SunnyRent_ADO.NET_Project/SunnyRent/SunnyRent/Views/Houses/AdminDetailsView.cshtml
@model SunnyRent.ViewModel.HouseReservationViewModel
@{
    ViewBag.Title = "AdminDetailsView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" runat="server" media="screen" href="~/Content/myCss.css" />

<div class="row">
    <div class="col-md-9 firstCell">
        <div class="container" style="width:95%">
            <h2>@Model.House.Name</h2>
            @*<div class="col-md-4">*@
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                    <li data-target="#myCarousel" data-slide-to="3"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active ">
                        <img src="~/Photoes/cottages/@Url.Content(@Model.House.Image[0].ImagePath)" alt="image1" style="width:800px; height:600px">
                    </div>

                    <div class="item ">
                        <img src="~/Photoes/cottages/@Url.Content(@Model.House.Image[1].ImagePath)" alt="image2" style="width:800px; height:600px">
                    </div>

                    <div class="item ">
                        <img src="~/Photoes/cottages/@Url.Content(@Model.House.Image[2].ImagePath)" alt="image3" style="width:800px; height:600px">
                    </div>

                    <div class="item ">
                        <img src="~/Photoes/cottages/@Url.Content(@Model.House.Image[3].ImagePath)" alt="image4" style="width:800px; height:600px">
                    </div>
                </div>



                @*Left and right controls*@
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            @*</div>*@
        </div>
    </div>
    <div class="col-md-3 secondCell">
        <div class="descrip">
            <h3>Description</h3>
            <p>
                @Model.House.Description
            </p>
        </div>
    </div>

    <div class="row thirdCell">
        <div class="col-md-4">
            <h3>Location</h3>
            <p>
                @Model.House.Address
            </p>
        </div>
        <div class="col-md-4">
            <h3>Rates</h3>
            <p>
                @Model.House.Rate $/week
            </p>
        </div>
        <div class="col-md-4">
            <h3>Availability</h3>

            <p>
                @*
                           @Html.TextBox("CheckIn", String.Format("{0:d}", Model.ToString()),
                    new { @class = "datefield", id = "datepicker", type = "date" })


                               @using (Html.BeginForm())
                               {
                                   @Html.EditorFor(r => r.Reservations, new { HtmlTextWriterAttribute = new { @class = "datefield" } })
                               }
                *@
            </p>
            <p>Date: <input type="text" class="datefield" id="datepicker"></p>
        </div>
    </div>

</div>



<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

<link href="@Url.Content("~/Content/themes/base/jquery.ui.core.css")"
      rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/jquery.ui.datepicker.css")"
      rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/jquery.ui.theme.css")"
      rel="stylesheet" type="text/css" />

<script src="@Url.Content("~/Scripts/jquery.ui.core.min.js")"
        type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.ui.datepicker.min.js")"
        type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/DatePickerReady.js")"
        type="text/javascript"></script>



@{
    var bookedDates = new List<String>();
    foreach (var res in Model.Reservations)
    {
        var checkIn = res.CheckIn;
        var checkOut = res.CheckOut;
        bookedDates.Add(checkIn.Date.ToString("d"));

        int d = (checkOut.Day - checkIn.Day);

        for (var i = 0; i <= d; i++)
        {
            var date = checkIn.AddDays(i);
            bookedDates.Add(date.Date.ToString("d"));

        }
    }
    bookedDates.ToArray();
}

@section scripts{
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>

            var array = @Html.Raw(Json.Encode(bookedDates))

            $(function () {
                $(".datefield").datepicker(
                    {
                        dateFormat: "dd/mm/yy",
                        // minDate: 20, maxDate: "+1M +10D"
                        beforeShowDay: function (date) {
                            var string = jQuery.datepicker.formatDate('yy-mm-dd', date);
                            return [array.indexOf(string) == -1]
                        }

                    });
            });

    </script>

}

SunnyRent_ADO.NET_Project/SunnyRent/SunnyRent/Views/Houses/AdminView.cshtml
@model IEnumerable<SunnyRent.Models.House>
@{
    ViewBag.Title = "AdminView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" runat="server" media="screen" href="~/Content/myCss.css" />
<h2>Cottages</h2>
@foreach (var house in Model)
{
    <div class="row" id="wholeDiv">
        <div class="col-md-4">

            <img style="width:350px; height:250px" src="~/Photoes/cottages/@Url.Content(house.Image[0].ImagePath)" />

        </div>
        <div class="col-md-4">
            <h3>@house.Name</h3>
            <h4>@house.Address</h4>
            <div class="divIcons">
                @if (house.Pet)
                {
                    <img class="myIcons" src="~/Photoes/dog.png" />
                }

                @if (house.TV)
                {
                    <img class="myIcons" src="~/Photoes/television.png" />
                }

                @if (house.WiFi)
                {
                    <img class="myIcons" src="~/Photoes/wifi.png" />
                }

                @if (house.BBQ)
                {
                    <img class="myIcons" src="~/Photoes/bbq.png" />
                }

                @if (house.AccessToWater)
                {
                    <img class="myIcons" src="~/Photoes/sea.png" />
                }

                @if (!house.Smoking)
                {
                    <img class="myIcons" src="~/Photoes/no-smoking-sign.png" />
                }

                @if (house.Pool)
                {
                    <img class="myIcons" src="~/Photoes/swimming-pool.png" />
                }

                @if (house.FirePlace)
                {
                    <img class="myIcons" src="~/Photoes/fireplace.png" />
                }

            </div>
        </div>
        <div class="col-md-4" style="padding-left:5%">
            <h2>@house.Rate$/week</h2>
            <h3>@Html.ActionLink("Details", "Details", "Houses", new { id = house.Id }, new { @class = "btn btn-primary button" })</h3>
            <h3>@Html.ActionLink("Edit", "Edit", "Houses", new { id = house.Id }, new { @class = "btn btn-primary button" })</h3>
            <h3>@Html.ActionLink("Delete", "Delete", "Houses", new { id = house.Id }, new { @class = "btn btn-primary button" })</h3>
        </div>
    </div>

}

<br />
<p>@Html.ActionLink("Add New Cottage", "New", "Houses", null, new { @class = "btn btn-default buttonAdd" }) </p>

SunnyRent_ADO.NET_Project/SunnyRent/SunnyRent/Views/Houses/CustomerDetailsView.cshtml
@model SunnyRent.ViewModel.HouseReservationViewModel
@{
    ViewBag.Title = "CustomerDetailsView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" runat="server" media="screen" href="~/Content/myCss.css" />

<div class="row">
    <div class="col-md-9 firstCell">
        <div class="container" style="width:95%">
            <h2>@Model.House.Name</h2>
            @*<div class="col-md-4">*@
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                    <li data-target="#myCarousel" data-slide-to="3"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active ">
                        <img src="~/Photoes/cottages/@Url.Content(@Model.House.Image[0].ImagePath)" alt="image1" style="width:800px; height:600px">
                    </div>

                    <div class="item ">
                        <img src="~/Photoes/cottages/@Url.Content(@Model.House.Image[1].ImagePath)" alt="image2" style="width:800px; height:600px">
                    </div>

                    <div class="item ">
                        <img src="~/Photoes/cottages/@Url.Content(@Model.House.Image[2].ImagePath)" alt="image3" style="width:800px; height:600px">
                    </div>

                    <div class="item ">
                        <img src="~/Photoes/cottages/@Url.Content(@Model.House.Image[3].ImagePath)" alt="image4" style="width:800px; height:600px">
                    </div>
                </div>



                @*Left and right controls*@
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            @*</div>*@
        </div>
    </div>
    <div class="col-md-3 secondCell">
        <div class="descrip">
            <h3>Description</h3>
            <p>
                @Model.House.Description
            </p>
        </div>
    </div>

    <div class="row thirdCell">
        <div class="col-md-4">
            <h3>Location</h3>
            <p>
                @Model.House.Address
            </p>
        </div>
        <div class="col-md-4">
            <h3>Rates</h3>
            <p>
                @Model.House.Rate $/week
            </p>
        </div>
        <div class="col-md-4">
            <h3>Availability</h3>

            <p>
                @*
                           @Html.TextBox("CheckIn", String.Format("{0:d}", Model.ToString()),
                    new { @class = "datefield", id = "datepicker", type = "date" })


                               @using (Html.BeginForm())
                               {
                                   @Html.EditorFor(r => r.Reservations, new { HtmlTextWriterAttribute = new { @class = "datefield" } })
                               }
                *@
            </p>
            <p>Date: <input type="text" class="datefield" id="datepicker"></p>
        </div>
    </div>
    <div class="row">
        <div id="bookNow">

            @*<input type="submit" class="btn btn-success btn-lg btn-block" value="Book" />*@
            <h3> @Html.ActionLink("Book", "Book", "Reservations", new { id = Model.House.Id }, new { @class = "btn btn-success btn-lg bookbtn" })</h3>
        </div>

    </div>
</div>



<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

<link href="@Url.Content("~/Content/themes/base/jquery.ui.core.css")"
      rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/jquery.ui.datepicker.css")"
      rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/jquery.ui.theme.css")"
      rel="stylesheet" type="text/css" />

<script src="@Url.Content("~/Scripts/jquery.ui.core.min.js")"
        type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.ui.datepicker.min.js")"
        type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/DatePickerReady.js")"
        type="text/javascript"></script>



@{
    var bookedDates = new List<String>();
    foreach (var res in Model.Reservations)
    {
        var checkIn = res.CheckIn;
        var checkOut = res.CheckOut;
        bookedDates.Add(checkIn.Date.ToString("d"));

        int d = (checkOut.Day - checkIn.Day);

        for (var i = 0; i <= d; i++)
        {
            var date = checkIn.AddDays(i);
            bookedDates.Add(date.Date.ToString("d"));

        }
    }
    bookedDates.ToArray();
}

@section scripts{
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>

            var array = @Html.Raw(Json.Encode(bookedDates))

            $(function () {
                $(".datefield").datepicker(
                    {
                        dateFormat: "dd/mm/yy",
                        // minDate: 20, maxDate: "+1M +10D"
                        beforeShowDay: function (date) {
                            var string = jQuery.datepicker.formatDate('yy-mm-dd', date);
                            return [array.indexOf(string) == -1]
                        }

                    });
            });

    </script>

}

SunnyRent_ADO.NET_Project/SunnyRent/SunnyRent/Views/Houses/Details.cshtml
@model SunnyRent.ViewModel.HouseReservationViewModel
@{
    ViewBag.Title = "Details";
}
<link rel="stylesheet" runat="server" media="screen" href="~/Content/myCss.css" />

<div class="row">
    <div class="col-md-9 firstCell">
        <div class="container" style="width:95%">
            <h2>@Model.House.Name</h2>
            @*<div class="col-md-4">*@
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                        <li data-target="#myCarousel" data-slide-to="3"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        <div class="item active ">
                            <img src="~/Photoes/cottages/@Url.Content(@Model.House.Image[0].ImagePath)" alt="image1" style="width:800px; height:600px">
                            @*<img src="" alt="Los Angeles" style="width:800px; height:600px">*@
                        </div>

                        <div class="item ">
                            <img src="~/Photoes/cottages/@Url.Content(@Model.House.Image[1].ImagePath)" alt="image2" style="width:800px; height:600px">
                            @*<img src="" alt="Chicago" style="width:800px; height:600px">*@
                        </div>

                        <div class="item ">
                            <img src="~/Photoes/cottages/@Url.Content(@Model.House.Image[2].ImagePath)" alt="image3" style="width:800px; height:600px">
                            @*<img src="" alt="New york" style="width:800px; height:600px">*@
                        </div>

                        <div class="item ">
                            <img src="~/Photoes/cottages/@Url.Content(@Model.House.Image[3].ImagePath)" alt="image4" style="width:800px; height:600px">
                            @*<img src="" alt="New york" style="width:800px; height:600px">*@
                        </div>
                    </div>



                    Left and right controls
                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            @*</div>*@
        </div>
    </div>
    <div class="col-md-3 secondCell">
        <div class="descrip">
            <h3>Description</h3>
            <p>
                @Model.House.Description
            </p>
        </div>
    </div>

    <div class="row thirdCell">
        <div class="col-md-4">
            <h3>Location</h3>
            <p>
                @Model.House.Address
            </p>
        </div>
        <div class="col-md-4">
            <h3>Rates</h3>
            <p>
                @Model.House.Rate $/week
            </p>
        </div>
        <div class="col-md-4">
            <h3>Availability</h3>

            <p>
                @*
               @Html.TextBox("CheckIn", String.Format("{0:d}", Model.ToString()),
        new { @class = "datefield", id = "datepicker", type = "date" })


                   @using (Html.BeginForm())
                   {
                       @Html.EditorFor(r => r.Reservations, new { HtmlTextWriterAttribute = new { @class = "datefield" } })
                   }
                *@
            </p>
             <p>Date: <input type="text" class="datefield" id="datepicker"></p>
        </div>
    </div>
    <div class="row" >
        <div id="bookNow">

            @*<input type="submit" class="btn btn-success btn-lg btn-block" value="Book" />*@
            <h3> @Html.ActionLink("Book", "Book", "Reservations", new { id = Model.House.Id }, new { @class = "btn btn-success btn-lg bookbtn" })</h3>
        </div>
      
    </div>
</div>



<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

<link href="@Url.Content("~/Content/themes/base/jquery.ui.core.css")"
      rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/jquery.ui.datepicker.css")"
      rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/jquery.ui.theme.css")"
      rel="stylesheet" type="text/css" />

<script src="@Url.Content("~/Scripts/jquery.ui.core.min.js")"
        type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.ui.datepicker.min.js")"
        type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/DatePickerReady.js")"
        type="text/javascript"></script>



@{
    var bookedDates = new List<String>();
    foreach (var res in Model.Reservations)
    {
        var checkIn = res.CheckIn;
        var checkOut = res.CheckOut;
        bookedDates.Add(checkIn.Date.ToString("d"));

        int d = (checkOut.Day - checkIn.Day);

        for (var i = 0; i <= d; i++)
        {
            var date = checkIn.AddDays(i);
            bookedDates.Add(date.Date.ToString("d"));
            
        }
    }
    bookedDates.ToArray();
    }

    @section scripts{
        <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

        <script>           
            var array = @Html.Raw(Json.Encode(bookedDates))
            
            $(function () {
                $(".datefield").datepicker(
                    {
                        dateFormat: "dd/mm/yy",
                        // minDate: 20, maxDate: "+1M +10D"
                        beforeShowDay: function (date) {
                            var string = jQuery.datepicker.formatDate('yy-mm-dd', date);
                            return [array.indexOf(string) == -1]
                        }

                    });
            });

        </script>

    }